#!/usr/bin/env python

from pylab import *
#read csv file generated by excel
#plot schedule for each room
#plot schedule for each faculty member

def drawbox(data,style):#feed in center x1,x2,y1,y2,rotation E of N
    #xcoords of unrotated box, going around CCW
    xl=array([data[0],data[1],data[1],data[0],data[0]],'d')
    yl=array([data[2],data[2],data[3],data[3],data[2]],'d')

    plot(xl,yl,style)
#    ang=data[4]*pi/180.#convert rotation to radians
#    #rotate coordinates
#    xp=cos(ang)*xl-sin(ang)*yl
#    yp=sin(ang)*xl+cos(ang)*yl
    #draw rotated box
#    plot(xp,yp,style)

def readSchedule(file):
    block=[]
    room=[]
    fac=[]
    credit=[]
    course=[]
    for line in file:
        if line.startswith('CRN'):
            continue
        t=line.split(',')
        try:
            course.append(t[2])
            block.append(t[4])
            room.append(t[7])
            fac.append(t[8])
            credit.append(t[9])
        except:
            print "Error reading line: ",line
            continue
    return block,room,fac,credit,course
#dictionary to connect section number to time/day

def fixplots(nfig,list,nx,ny):
    figure(nfig)
    for i in range(len(list)):
        subplot(nx,ny,i+1)
        title(list[i],fontsize=12)
        #axis([1,6,8,22])
        axis([1,6,22,8])
        location=xticks()
        location=location[0]
        xticks(location[0:-1]+.5,('M','T','W','R','F'),horizontalalignment='center',fontsize=10)
        yticks(fontsize=10)

sectionTime={'01':[8.,9],'03':[9.+10./60,10.+10./60],'05':[10.+20./60,11+20./60],'07':[11.5,12.5],'7M':[11.5,12.5],'7W':[11.5,12.5],'09':[12+1.5,12+2.5],'11':[12+2+40./60,12+3+40./60],'13':[12+3+50./60,12+5.25],'15':[12+3.+50./60,12+4+50./60],'7E':[12+6.,12+8+50./60],'9E':[12+6.,12+8+50./60],'02':[8.,9+25./60],'04':[9+35./60,11.],'06':[11+10./60,12.+35./60],'08':[12+1.,12+2+25./60],'10':[12+2+35./60,12+4.],'12':[12+4.+10./60,12+5+35./60],'6E':[12+6.,12+8+50./60],'8E':[12+6.,12+8+50./60],'MM':[8.+30./60,11.+30./60],'BM':[12+2.+40./60,12+5.+40./60],'BT':[12+2+40./60,12+5.+40./60],'BW':[12+2.+40./60,12+5.+40./60],'BR':[12+2.+40./60,12+5.+40./60],'BF':[12+2.+40./60,12+5.+40./60],'13W':[12+3+50./60,12+4+50./60],'13M':[12+3+50./60,12+4+50./60],'9M':[12+1.5,12+2.5],'9W':[12+1.5,12+2.5],'9F':[12+1.5,12+2.5],'07W':[11.5,12.5],'07M':[11.5,12.5],'U46':[10.+55./60,12+40./60],'05W':[10.+20./60,11+20./60],'3W':[9.+10./60,10.+10./60],'5W':[10.+20./60,11+20./60],'11M':[12+2+40./60,12+3+40./60],'PF':[12+1+30./60,12+4+30./60],}

#days M=1, T=2, We=3, Th=4, F=5
sectionDays={'01':[1,3,5],'03':[1,3,5],'05':[1,3,5],'07':[1,3,5],'09':[1,3,5],'11':[1,3,5],'13':[1,3],'15':[1,3,5],'7E':[1],'9E':[3],'02':[2,4],'04':[2,4],'06':[2,4],'08':[2,4],'10':[2,4],'12':[2,4],'6E':[2],'8E':[4],'BM':[1],'BT':[2],'BW':[3],'BR':[4],'BF':[5],'13M':[1],'13W':[3],'9M':[1],'9W':[3],'9F':[5],'7M':[1],'7W':[3],'7F':[5],'U46':[2,4],'05W':[3],'3W':[3],'5W':[3],'11M':[1],'PF':[5],'7E':[1],'MM':[1]}
#allfac=['Bellis','Coohill','Cummings','Finn','Hassel','McColgan','Medsker','Moustakas','Rosenberry','Vernizzi','Caldaro','Broder', 'Mannikarottu','Gigante','Marr','TBD']
allfac=['Bellis','Coohill','Cummings','Finn','Hassel','McColgan','Medsker','Moustakas','Rosenberry','Vernizzi','Caldaro','Broder']
FacFigNumber=dict((a,b) for a,b in zip(allfac,arange(len(allfac))+1))
#FacFigNumber={'Bellis':1,'Coohill':2,'Cummings':3,'Finn':4,'McColgan':5,'Rosenberry':6,'Vernizzi':7,'Medsker':8,'Moustakas':9,'Hassel':10,'Caldaro':11,'Broder':12, 'Mannikarottu':13,'TBD':14}
#read input file
file=open('/Users/rfinn/siena/PhysicsDept/Schedules/ScheduleS14.csv','r')
#file=open('/Users/rfinn/siena/PhysicsDept/Schedules/ScheduleF12.v2.csv','r')
#file=open('/Users/rfinn/siena/PhysicsDept/Schedules/ScheduleS12.csv','r')
block,room,fac,credit,course=readSchedule(file)

#plot schedules by room
PhysRooms=['RB 144','RB 136','RB 104','RB 250']
figure(1,figsize=(20,12))
nx=1
ny=4
clf()
subplots_adjust(left=.05,right=.95,top=.95,bottom=.05,wspace=.1,hspace=.1)

for i in range(len(block)):
    if block[i].find('00')> -1:
        continue
    try:
        days=sectionDays[block[i]]
    except:
        print "Error reading days for block ",block[i]
        continue
    for d in days:
        dbox=[d+.05,d+1-.05]
        try:
            boxdata=dbox+sectionTime[block[i]]
        except:
            print "Error reading block ",block[i]
            continue
        #print room[i]
        if room[i].find('144') > -1:
            subplot(nx,ny,1)
        if room[i].find('136') > -1:
            subplot(nx,ny,2)
        if room[i].find('104') > -1:
            subplot(nx,ny,3)
        if room[i].find('250') > -1:
            subplot(nx,ny,4)
        
        drawbox(boxdata,'k-')
        #print 'got here, boxdata = ',boxdata
        ax=gca()
        #print (boxdata[0]+boxdata[1])/2.,(boxdata[2]+boxdata[3])/2.,course[i]
        s=course[i]+'\n'+fac[i]
        text((boxdata[0]+boxdata[1])/2.,(boxdata[2]+boxdata[3])/2.,s,horizontalalignment='center',verticalalignment='center',fontsize=10)


#plot faculty schedules
#for i in range(len(PhysRooms)):
#    subplot(nx,ny,i+1)
#    axis([1,6,8,22])


figure(2,figsize=(15,10))
clf()
subplots_adjust(left=.05,right=.95,wspace=.09,hspace=.2,top=.95,bottom=.05)
for i in range(len(block)):
    if block[i].find('00')> -1:
        continue
    try:
        days=sectionDays[block[i]]
    except:
        print "Error reading days for block ",block[i]
        continue
    try:
        instr=fac[i]
        nsubplot=FacFigNumber[instr]
        subplot(3,4,nsubplot)
    except:
        print "Error reading instructor ",fac[i]
    for d in days:
        dbox=[d+.05,d+1-.05]
        try:
            boxdata=dbox+sectionTime[block[i]]
        except:
            print "Error reading block ",block[i]
            continue
        #print room[i]
        drawbox(boxdata,'k-')
        ax=gca()
        #print (boxdata[0]+boxdata[1])/2.,(boxdata[2]+boxdata[3])/2.,course[i]
        s=course[i]#+' \n '+fac[i]
        text((boxdata[0]+boxdata[1])/2.,(boxdata[2]+boxdata[3])/2.,s,horizontalalignment='center',verticalalignment='center',fontsize=9)
fixplots(2,allfac,3,4)

fixplots(1,PhysRooms,nx,ny)

#mark where math courses are
#mathblock=['04','10','9M','11M','3W','5W']
#mathcourse=['ApplI','CalcIII','CalcIIIL','CalcIIIL','CalcIIIL','CalcIIIL']

mathblock=['07','10','9M','9W','12','13M','07']
mathcourse=['Linear','DiffEq','DiffEqL','DiffEqL','CalcIII','CalcIIIL','CompAlg']

figure(1)

for i in range(len(mathblock)):
    try:
        days=sectionDays[mathblock[i]]
    except:
        print "Error reading days for block ",mathblock[i]
        continue
    for d in days:
        dbox=[d+.1,d+1-.1]
        try:
            boxdata=dbox+sectionTime[mathblock[i]]
        except:
            print "Error reading block ",mathblock[i]
            continue
        #print room[i]
        for j in range(1,4):
            subplot(nx,ny,j)
            drawbox(boxdata,'g-')
            ax=gca()
        #print (boxdata[0]+boxdata[1])/2.,(boxdata[2]+boxdata[3])/2.,course[i]
            s=mathcourse[i]#+' \n '+fac[i]
            text((boxdata[0]+boxdata[1])/2.,(boxdata[2]+boxdata[3])/2.-.4,s,horizontalalignment='center',verticalalignment='center',fontsize=8,color='g')



#fig 5 - coohill

#fig 6 - 
figure(1)
#savefig('Fall2012ByRoom.png')
savefig('Spring2014ByRoom.png')
figure(2)
savefig('Spring2014ByFaculty.png')
