#!/usr/bin/env python
import pyfits
from LCScommon import *
from pylab import *
import os
import mystuff as my


def loadmastertable(clustername):
    infile='/home/rfinn/research/LocalClusters/MasterTables/'+clustername+'mastertable.fits'
    tb=pyfits.open(infile)
    tbdata=tb[1].data
    tb.close()
    self.agcflag=tbdata.field('AGCflag')
    self.HIflag=tbdata.field('HIFLAG')
    self.sdssflag=tbdata.field('SDSSflag')
    self.sdssphotflag=tbdata.field('SDSSphotflag')
    self.mpaflag=tbdata.field('MPAFLAG')
    self.apexflag=tbdata.field('APEXFLAG')
    self.sexsdssflag=tbdata.field('SEXSDSSflag')
    self.sex24flag=tbdata.field('SEX24FLAG')
    self.agcvoptflag=tbdata.field('AGCVOPTFLAG')
    
    self.agcnumber=tbdata.field('AGCNUMBER')
    self.raagc=tbdata.field('AGCRA')
    self.decagc=tbdata.field('AGCDEC')
    self.a100=tbdata.field('A100')
    self.b100=tbdata.field('B100')
    self.mag10=tbdata.field('MAG10')
    self.posang=tbdata.field('POSANG')
    self.bsteintype=tbdata.field('BSTEINTYPE')
    self.vopt=tbdata.field('VOPT')
    self.verr=tbdata.field('VERR')
    self.vsource=tbdata.field('VSOURCE')
    self.flux100=tbdata.field('FLUX100')
    self.rms100=tbdata.field('RMS100')
    self.v21=tbdata.field('V21')
    self.width=tbdata.field('WIDTH')
    self.widtherr=tbdata.field('WIDTHERR')
    #sdss info
    self.sdssra=tbdata.field('SDSSRA')
    self.sdssdec=tbdata.field('SDSSDEC')
    self.sdssphotra=tbdata.field('SDSSphotRA')
    self.sdssphotdec=tbdata.field('SDSSphotDEC')
    self.sdssu=tbdata.field('SDSSU')
    self.sdssg=tbdata.field('SDSSG')
    self.sdssr=tbdata.field('SDSSR')
    self.sdssi=tbdata.field('SDSSI')
    self.sdssz=tbdata.field('SDSSZ')
    self.sdssspecz=tbdata.field('SDSSSPECZ')
    self.sdssvopt=tbdata.field('SDSSVOPT')
    self.sdsshaew=tbdata.field('SDSSHAEW')
    self.sdsshaewerr=tbdata.field('SDSSHAEWERR')
    self.sdssplate=tbdata.field('SDSSPLATE')
    self.sdssfiberid=tbdata.field('SDSSFIBERID')
    self.sdsstile=tbdata.field('SDSSTILE')
    self.mpahalpha=tbdata.field('MPAHALPHA')
    self.mpahbeta=tbdata.field('MPAHBETA')
    self.mpao3=tbdata.field('MPAOIII')
    self.mpan2=tbdata.field('MPANII')
    #sextractor info
    self.numberser=tbdata.field('NUMBERSER')
    self.ximageser=tbdata.field('XIMAGESER')
    self.yimageser=tbdata.field('YIMAGESER')
    self.xminimageser=tbdata.field('XMINIMAGESER')
    self.xmaximageser=tbdata.field('XMAXIMAGESER')
    self.yminimageser=tbdata.field('YMINIMAGESER')
    self.raser=tbdata.field('RASER')
    self.decser=tbdata.field('DECSER')
    self.fluxisoser=tbdata.field('FLUXISOSER')
    self.fluxerrisoser=tbdata.field('FLUXERRISOSER')
    self.magisoser=tbdata.field('MAGISOSER')
    self.magerrisoser=tbdata.field('MAGERRISOSER')
    self.fluxautoser=tbdata.field('FLUXAUTOSER')
    self.fluxerrautoser=tbdata.field('FLUXERRAUTOSER')
    self.magautoser=tbdata.field('MAGAUTOSER')
    self.magerrautoser=tbdata.field('MAGERRAUTOSER')
    self.fluxpetroser=tbdata.field('FLUXPETROSER')
    self.fluxerrpetroser=tbdata.field('FLUXERRPETROSER')
    self.magpetroser=tbdata.field('MAGPETROSER')
    self.magerrpetroser=tbdata.field('MAGERRPETROSER')
    self.kronradser=tbdata.field('KRONRADSER')#kron radius
    self.petroradser=tbdata.field('PETRORADSER')#petrosian radius
    self.fluxradser=tbdata.field('FLUXRADSER')#1/2 light radius
    self.isoareaser=tbdata.field('ISOAREASER')
    self.aworldser=tbdata.field('AWORLDSER')
    self.bworldser=tbdata.field('BWORLDSER')
    self.thetaser=tbdata.field('THETASER')
    self.errthetaser=tbdata.field('ERRTHETASER')
    self.thetaj2000ser=tbdata.field('THETAJ2000SER')
    self.errthetaj2000ser=tbdata.field('ERRTHETAJ2000SER')
    self.elongser=tbdata.field('ELONGATIONSER')
    self.elliptser=tbdata.field('ELLIPTICITYSER')
    self.fwhmser=tbdata.field('FWHMSER')
    self.flagsser=tbdata.field('FLAGSSER')
    self.classstarser=tbdata.field('CLASSSTARSER')
    #SEXTRACTOR  output 24 micron data
    self.numberse24=tbdata.field('NUMBERSE24')
    self.ximagese24=tbdata.field('XIMAGESE24')
    self.yimagese24=tbdata.field('YIMAGESE24')
    self.xminimagese24=tbdata.field('XMINIMAGESE24')
    self.xmaximagese24=tbdata.field('XMAXIMAGESE24')
    self.xminimagese24=tbdata.field('YMINIMAGESE24')
    self.rase24=tbdata.field('RASE24')
    self.decse24=tbdata.field('DECSE24')
    self.fluxisose24=tbdata.field('FLUXISOSE24')
    self.fluxerrisose24=tbdata.field('FLUXERRISOSE24')
    self.magisose24=tbdata.field('MAGISOSE24')
    self.magerrisose24=tbdata.field('MAGERRISOSE24')
    self.fluxautose24=tbdata.field('FLUXAUTOSE24')
    self.fluxerrautose24=tbdata.field('FLUXERRAUTOSE24')
    self.magautose24=tbdata.field('MAGAUTOSE24')
    self.magerrautose24=tbdata.field('MAGERRAUTOSE24')
    self.fluxpetrose24=tbdata.field('FLUXPETROSE24')
    self.fluxerrpetrose24=tbdata.field('FLUXERRPETROSE24')
    self.magpetrose24=tbdata.field('MAGPETROSE24')
    self.magerrpetrose24=tbdata.field('MAGERRPETROSE24')
    self.kronradse24=tbdata.field('KRONRADSE24')
    self.petroradse24=tbdata.field('PETRORADSE24')
    self.fluxradse24=tbdata.field('FLUXRADSE24')
    self.isoarease24=tbdata.field('ISOAREASE24')
    self.aworldse24=tbdata.field('AWORLDSE24')
    self.bworldse24=tbdata.field('BWORLDSE24')
    self.thetase24=tbdata.field('THETASE24')
    self.errthetase24=tbdata.field('ERRTHETASE24')
    self.thetaj2000se24=tbdata.field('THETAJ2000SE24')
    self.errthetaj2000se24=tbdata.field('ERRTHETAJ2000SE24')
    self.elongse24=tbdata.field('ELONGATIONSE24')
    self.elliptse24=tbdata.field('ELLIPTICITYSE24')
    self.fwhmse24=tbdata.field('FWHMSE24')
    self.flagsse24=tbdata.field('FLAGSSE24')
    self.classstarse24=tbdata.field('CLASSSTARSE24')
    self.f24dist=self.fluxautose24[self.sex24flag]
    #apex output
    self.mipsra=tbdata.field('MIPSRA')
    self.mipsdec=tbdata.field('MIPSDEC')
    self.mipsflux=tbdata.field('MIPSFLUX')
    self.mipsfluxerr=tbdata.field('MIPSFLUXERR')
    self.mipssnr=tbdata.field('MIPSSNR')
    self.mipsdeblend=tbdata.field('MIPSDEBLEND')
    self.mipsfluxap1=tbdata.field('MIPSFLUXAP1')
    self.mipsfluxap1err=tbdata.field('MIPSFLUXAP1ERR')
    self.mipsfluxap2=tbdata.field('MIPSFLUXAP2')
    self.mipsfluxap2err=tbdata.field('MIPSFLUXAP2ERR')
    self.mipsfluxap3=tbdata.field('MIPSFLUXAP3')
    self.mipsfluxap4err=tbdata.field('MIPSFLUXAP3ERR')
    
    
    self.On24ImageFlag=tbdata.field('On24ImageFlag')
    self.supervopt=tbdata.field('SUPERVOPT')
    self.ra=tbdata.field('SUPERRA')
    self.dec=tbdata.field('SUPERDEC')
    
    
    
    self.stellarmass=tbdata.field('STELLARMASS')
    
    self.sdssMu=tbdata.field('SDSSMU')
    self.sdssLu=tbdata.field('SDSSLU')
    self.sdssMg=tbdata.field('SDSSMG')
    self.sdssLg=tbdata.field('SDSSLG')
    self.sdssMr=tbdata.field('SDSSMR')
    self.sdssLr=tbdata.field('SDSSLR')
    self.sdssMi=tbdata.field('SDSSMI')
    self.sdssLi=tbdata.field('SDSSLI')
    self.sdssMz=tbdata.field('SDSSMZ')
    self.sdssLz=tbdata.field('SDSSLZ')
    self.membflag =tbdata.field('MEMBFLAG')
    self.morphflag =tbdata.field('MORPHFLAG')
    self.morph =tbdata.field('MORPH')
    self.disturb =tbdata.field('DISTURB')
    self.localdens =tbdata.field('LOCALDENS')
    self.agn1 =tbdata.field('AGNKAUFF')
    self.agn2 =tbdata.field('AGNKEWLEY')
    self.agn3 =tbdata.field('AGNSTASIN')
    self.logn2halpha=log10(self.mpan2/self.mpahalpha)
    self.logo3hbeta=log10(self.mpao3/self.mpahbeta)
    self.ellipseflag24 =tbdata.field('ELLIPSEFLAG24')
    self.ellipseflagsdss =tbdata.field('ELLIPSEFLAGSDSS')
    self.ellipseflag =tbdata.field('ELLIPSEFLAG')
    
    # galaxy zoo fields
    self.galzooflag =tbdata.field('GALZOOFLAG')
    self.galzoonvote =tbdata.field('GALZOONVOTE')
    self.galzoopel =tbdata.field('GALZOOPEL')
    self.galzoopcw =tbdata.field('GALZOOPCW')
    self.galzoopacw =tbdata.field('GALZOOPACW')
    self.galzoopedge =tbdata.field('GALZOOPEDGE')
    self.galzoopdk =tbdata.field('GALZOOPDK')
    self.galzoopmg =tbdata.field('GALZOOPMG')
    self.galzoopcs =tbdata.field('GALZOOPCS')
    self.galzoopeldebiased =tbdata.field('GALZOOPELDEBIASED')
    self.galzoopcsdebiased =tbdata.field('GALZOOPCSDEBIASED')
    self.galzoospiral =tbdata.field('GALZOOSPIRAL')
    self.galzooelliptical =tbdata.field('GALZOOELLIPTICAL')
    self.galzoouncertain =tbdata.field('GALZOOUNCERTAIN')
    
    #end of master table!
    #self.spiralFlag=self.On24ImageFlag & self.galzooflag & self.ellipseflag & (self.galzoopcsdebiased > 0.6)
    self.spiralFlag=self.On24ImageFlag & self.galzooflag & self.ellipseflag & self.galzoospiral
